---
title: "Mini Project 3"
author: "Lauren Meyer, Neamat Sabry, Carol Milton"
date: "4/12/2019"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sf)
library(leaflet)
library(macleish)
```

```{r message=FALSE}
trails <- macleish_layers %>%
  pluck("trails") %>%
  mutate(len = st_length(geometry))
contours <- macleish_layers %>%
  pluck("contours_3m")

joined <- st_join(trails, contours)
```

```{r include=FALSE}

get_height <- function(trail_name) {
  joined %>% filter(name == trail_name) %>%
    summarize(trailname = trail_name, max_h = max(ELEV_M), min_h = min(ELEV_M), diff_h = max_h - min_h,length = max(len), difficulty = diff_h * 2 * length) %>%
  mutate(difficulty = sqrt(as.numeric(length) * 2 * diff_h))
}

get_height("Poplar Hill Road")

names <- trails$name

difficulty_ratings <- map_dfr(trails$name, get_height)
```

```{r}
difficulty_ratings <- difficulty_ratings%>%
  mutate(rating = ifelse(difficulty<=100, "Easy",
                         ifelse(difficulty<300, "Moderate",
                         ifelse(difficulty>=300, "Hard", NA)))) %>%
  na.omit()
```


```{r}
pal <- colorFactor("YlOrRd", domain = difficulty_ratings$rating)
plot <- leaflet() %>%
  addTiles() %>%
  addPolylines(data = difficulty_ratings, color = ~pal(rating), opacity = 1)
plot
```

